<?php $this->headScript()->appendFile('/js/jquery-1.3.min.js'); ?>
<?php $this->headScript()->appendFile('/js/documentation.js'); ?>
<?php $this->headLink()->appendStylesheet('/css/documentation.css'); ?>

<div id="container">
  <div id="content">
    <p />
  </div>
</div>

<div id="sidepanel">
  <div class="supplementary corners top right bottom left">
    
    <div id="topicmap">
      <?php echo $this->topicMap; ?>
    </div>
    
  </div>
</div>
