<?php $this->headScript()->appendFile('/js/jquery-1.3.min.js'); ?>
<?php $this->headScript()->appendFile('/kodify/js/lx_analyzer.js'); ?>
<?php $this->headScript()->appendFile('/kodify/js/kodify.js'); ?>
<?php $this->headScript()->appendFile('/kodify/js/lang/php.js'); ?>
<?php $this->headLink()->appendStylesheet('/kodify/themes/blackboard.css'); ?>
<?php $this->headScript()->appendFile('/js/documentation.js'); ?>
<?php $this->headLink()->appendStylesheet('/css/documentation.css'); ?>

<div id="container">
  <div id="content">
    
    <div class="doctopic">
      <?php echo $this->topicBody; ?>
    </div>
    
  </div>
</div>

<div id="sidepanel">
  <div id="v3docnote" class="supplementary secondary">
    
    <p><strong>NOTE:</strong> Documentation for version 3 is in the <a href="http://swiftmailer.org/wikidocs/">wiki</a>.</p>
    
  </div>
  
  <div class="supplementary corners top right bottom left">
    
    <div id="topicmap">
      <?php echo $this->topicMap; ?>
    </div>
    
  </div>
  
  
</div>
