<?php $this->headMeta()->appendName('keywords', 'swift mailer, swiftmailer, swiftmail, php mailer, phpmailer, oop mailer, bulk emailing'); ?>
<?php $this->headLink()->appendStylesheet('/css/homepage.css'); ?>
<div id="container">
  <div id="content">
    
    <h1>Free Feature-rich PHP Mailer</h1>
    
    <p class="homepageintro">
      Swift Mailer integrates into any web app written in PHP 5, offering a flexible and elegant
      object-oriented approach to sending emails with a multitude of features.
    </p>
    
    <ul class="featurelist">
      <li class="feature1"><span>Send emails using SMTP, sendmail, postfix or a custom Transport implementation of your own</span></li>
      <li class="feature2"><span>Support servers that require username &amp; password and/or encryption</span></li>
      <li class="feature3"><span>Protect from header injection attacks without stripping request data content</span></li>
      <li class="feature4"><span>Send MIME compliant HTML/multipart emails</span></li>
      <li class="feature5"><span>Use event-driven plugins to customize the library</span></li>
      <li class="feature6"><span>Handle large attachments and inline/embedded images with low memory use</span></li>
    </ul>
    
  </div>
</div>

<div id="sidepanel">
  <div id="downloadbox" class="supplementary iconbox corners top right bottom left">
    <a href="<?php echo $this->url(array(
      'controller'=>'download',
      'action'=>'download-file',
      'filename'=>$this->currentDownload()->getName()),
      'get-download'
    ); ?>"><img src="/images/download.png" alt="download" /></a>
    <dl>
      <dt><a rel="nofollow" href="<?php echo $this->url(array(
        'controller'=>'download',
        'action'=>'download-file',
        'filename'=>$this->currentDownload()->getName()),
        'get-download'
      ); ?>"><?php echo $this->escape($this->currentDownload()->getName()); ?></a></dt>
      <dd>
        <div class="releasedate"><?php echo $this->escape(date('j F Y', $this->currentDownload()->getTimeCreated())); ?></div>
        <div class="downloadsize">
          <?php echo $this->escape(number_format($this->currentDownload()->getSize())); ?> bytes
        </div>
        <a rel="nofollow" href="<?php echo $this->url(array(
          'controller'=>'download',
          'action'=>'download-file',
          'filename'=>$this->currentDownload()->getName()),
          'get-download'
        ); ?>">Download</a>
      </dd>
    </dl>
  </div>
  
  <div id="docbox" class="supplementary iconbox secondary">
    <a href="<?php echo $this->url(array('controller'=>'documentation', 'action'=>'load-file', 'topic'=>'introduction'), 'docs-file'); ?>"><img src="/images/docs.png" alt="documents" /></a>
    <dl>
      <dt><a href="<?php echo $this->url(array('controller'=>'documentation', 'action'=>'load-file', 'topic'=>'introduction'), 'docs-file'); ?>">Complete User Guide</a></dt>
      <dd>
        Read the documentation and see how Swift Mailer works
      </dd>
    </dl>
  </div>
  
  <div id="newsbox" class="supplementary secondary">
    <h2>Looking for a lead developer</h2>
    <p>
      Long term users have probably noticed the increasing duration between releases.
      Long story short &#8211; this project needs a new lead developer/project manager with the drive to
      keep it moving.  There are tickets being created in the bug tracker, features to be implemented, and
      users to support &#8211; could you be the person to handle this?
    </p>
    <p>
      If you're an experienced PHP developer with <abbr title="Test Driven Development">TDD</abbr> experience and would like to
      play a lead role in Swift Mailer's development, please contact me along with a rough CV/resume
      at <em>chris AT w3style DOT co DOT uk</em>. Mail experience is not required.
    </p>
    <p>
      Being in charge, obviously you'd have free reign to take on other developers/use other services as you need.
    </p>
    <p>
      <strong>IMPORTANT:</strong> This is a <em>volunteer</em> effort&#8230; you won't get paid (apart from donations,
      which are infrequent &#8211; see the <a href="http://pledgie.com/campaigns/4523">Pledgie campaign</a> on GitHub).
    </p>
  </div>
  
</div>
