<?php $this->headLink()->appendStylesheet('/css/homepage.css'); ?>
<div id="container">
  <div id="content">
    
    <h1>Free Feature-rich PHP Mailer</h1>
    
    <p class="homepageintro">
      Swift Mailer integrates into any web app written in PHP 5, offering a flexible and elegant
      object-oriented approach to sending emails with a multitude of features.
    </p>
    
    <ul class="featurelist">
      <li class="feature1">Send emails using SMTP, sendmail, postfix or a custom Transport implementation of your own</li>
      <li class="feature2">Support servers that require username &amp; password and/or encryption</li>
      <li class="feature3">Protect from header injection attacks without stripping request data content</li>
      <li class="feature4">Send MIME compliant HTML/multipart emails</li>
      <li class="feature5">Use event-driven plugins to customize the library</li>
      <li class="feature6">Handle large attachments and inline/embedded images with low memory use</li>
    </ul>
    
  </div>
</div>

<div id="sidepanel">
  <div id="downloadbox" class="supplementary corners top right bottom left">
    <a href="#"><img src="/images/download.png" alt="download" /></a>
    <dl>
      <dt><a href="#">Swift-4.0.0.tar.gz</a></dt>
      <dd>
        <div class="releasedate">22 February 2009</div>
        <div class="downloadsize">384KB</div> <a href="#">Download</a>
      </dd>
    </dl>
  </div>
  
  <div id="docbox" class="supplementary secondary">
    <a href="#"><img src="/images/docs.png" alt="documents" /></a>
    <dl>
      <dt><a href="#">Complete User Guide</a></dt>
      <dd>
        Read the documentation and see how Swift Mailer works
      </dd>
    </dl>
  </div>
  
  <div id="newsbox" class="supplementary secondary">
    <h2>New version, new website, new&#8230;</h2>
    <p>
      It's both the end of an era and the dawn of a new beginning for the Swift Mailer
      team.  Following the long success of version 3, Swift Mailer is back better than
      ever.
    </p>
    <p>
      Version 4 wipes the slate clean and starts over with a great demonstration of
      object-oriented design and a flexible interface that leaves its predecessor
      for dead.
    </p>
    <p>
      Not only has the library gone through some significant changes, so has the development
      team, growing from a sole developer to a four-strong team with some big ideas.  We're
      excited and we hope you will be too!
    </p>
  </div>
  
</div>