<div id="sidepanel">
  <div class="supplementary iconbox secondary">
    <a href="<?php echo $this->url(array('controller'=>'admin', 'action'=>'download-manager')); ?>"><img src="/images/download.png" alt="download" /></a>
    <dl>
      <dt><a href="<?php echo $this->url(array('controller'=>'admin', 'action'=>'download-manager')); ?>">Download Manager</a></dt>
      <dd>
        Register new distribution downloads into the database
      </dd>
    </dl>
  </div>
  
  <div class="supplementary iconbox secondary">
    <a href="#"><img src="/images/users.png" alt="users" /></a>
    <dl>
      <dt><a href="#">User Manager</a></dt>
      <dd>
        Add users, remove users, reset passwords
      </dd>
    </dl>
  </div>
  
  <div class="supplementary iconbox secondary">
    <a href="<?php echo $this->url(array('controller'=>'admin', 'action'=>'password-settings')); ?>"><img src="/images/lock.png" alt="lock" /></a>
    <dl>
      <dt><a href="<?php echo $this->url(array('controller'=>'admin', 'action'=>'password-settings')); ?>">Password Settings</a></dt>
      <dd>
        Change your password
      </dd>
    </dl>
  </div>
  
  <div class="supplementary iconbox secondary">
    <a href="#"><img src="/images/stats.png" alt="stats" /></a>
    <dl>
      <dt><a href="#">Download Statistics</a></dt>
      <dd>
        Monitor the health and uptake of the project
      </dd>
    </dl>
  </div>
  
  <div class="supplementary iconbox secondary">
    <a href="<?php echo $this->url(array('controller'=>'admin', 'action'=>'logout')); ?>"><img src="/images/quit.png" alt="quit" /></a>
    <dl>
      <dt><a href="<?php echo $this->url(array('controller'=>'admin', 'action'=>'logout')); ?>">Logout (<?php echo $this->escape($this->user->getUsername()); ?>)</a></dt>
      <dd>
        Quit this session and log out of the admin area.
      </dd>
    </dl>
  </div>
  
</div>
