---
#Users who can administer the site
User:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    username: string(255)
    password_hash: string(32)
    password_salt: blob(3)
    email: string(255)
    time_created: integer
  indexes:
    name_index:
      fields: ['username']
  options:
    type: INNODB
    collate: utf8_general_ci
    charset: utf8

#Available downloads
Download:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    filename: string(255)
    time_created: integer
    filesize: integer
    source:
      type: enum
      values: ['sourceforge', 'googlecode', 'github']
    revoked:
      type: boolean
      notnull: true
    stable:
      type: boolean
      default: true
      notnull: true
    version_number: string(255)
  indexes:
    time_index:
      fields: ['time_created']
    revoke_index:
      fields: ['revoked']
    version_index:
      fields: ['version_number(18)']
  options:
    type: INNODB
    collate: utf8_general_ci
    charset: utf8

#Download hits (for stats tracking)
DownloadEvent:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    download_id: integer
    time_created: integer
    ip_address: string(15)
  relations:
    Download:
      foreignType: one
  indexes:
    time_index:
      fields: ['time_created']
  options:
    type: INNODB
    collate: utf8_general_ci
    charset: utf8
