<!-- -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
    "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
     xml:lang="en" >
  <head>
    
    <?php echo $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8'); ?>
    
    <?php echo $this->headLink()->appendStylesheet('/css/global.css'); ?>
    
    <!--[if IE]>
    <link rel="stylesheet" type="text/css" href="/css/ie.css" />
    <script type="text/javascript" src="/js/jquery-1.3.min.js"></script>
    <script type="text/javascript" src="/js/DD_roundies_0.0.2a-min.js"></script>
    <script type="text/javascript" src="/js/DD_belatedPNG_0.0.7a-min.js"></script>
    <script type="text/javascript" src="/js/ie.js"></script>
    <![endif]-->
    
    <?php echo $this->headScript(); ?>
    
    <?php if (empty($this->headHtml)): ?>
      <title>
        <?php if (!empty($this->title)): ?>
          <?php echo $this->escape($this->title); ?> &#8211;
        <?php endif; ?>
        Swift Mailer
      </title>
    <?php else: ?>
      <?php echo $this->headHtml; ?>
    <?php endif; ?>
    
  </head>
  <body>
    <div id="layoutcontainer">
      
    <div id="layout">
      
      <div id="header" class="corners top right left">
        <div id="headercontent">
          <img id="logo" src="/images/logo.png" alt="Swift Mailer" />
          
          <div id="navigation">
            <ul>
              <li><a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'index'), 'default'); ?>">home</a></li>
              <li><a href="<?php echo $this->url(array('controller'=>'download', 'action'=>'index'), 'default'); ?>">download</a></li>
              <li><a href="<?php echo $this->url(array('controller'=>'documentation', 'action'=>'load-file', 'topic'=>'introduction'), 'docs-file'); ?>">documentation</a></li>
              <li><a href="<?php echo $this->url(array('controller'=>'bug', 'action'=>'index'), 'bugs'); ?>">bugs</a></li>
              <li><a href="<?php echo $this->url(array('controller'=>'contact', 'action'=>'index'), 'default'); ?>">contact</a></li>
              <li class="tab corners top right left"><a href="<?php echo $this->url(array(
                'controller'=>'download',
                'action'=>'download-file',
                'filename'=>$this->currentDownload()->getName()),
                'get-download'
              ); ?>">current <?php echo $this->escape($this->currentDownload()->getVersion()); ?></a></li>
            </ul>
          </div>
        </div>
      </div>

      <div id="wrapper" class="corners bottom right left">
        
        <div>
          <?php echo $this->layout()->content; ?>
          
        </div>
      
        <div id="footer">
          <div id="footercontent">
            
            <div id="about">
              <p><strong>&copy; 2009 Chris Corbyn</strong></p>
            </div>
        
        <div id="support">
          
          <dl class="contact">
            <dt>Swift Mailer</dt>
            <dd>
              <ul>
                <!--<li>About</li>-->
                <li><a href="<?php echo $this->url(array('controller'=>'contact', 'action'=>'index'), 'default'); ?>">Contact Information</a></li>
              </ul>
            </dd>
          </dl>
          
          <dl class="getstarted">
            <dt>Get Started</dt>
            <dd>
              <ul>
                <li><a href="<?php echo $this->url(array('controller'=>'download', 'action'=>'index'), 'default'); ?>">Download</a></li>
                <!--<li>Tutorials</li>-->
                <li><a href="<?php echo $this->url(array('controller'=>'documentation', 'action'=>'index'), 'docs'); ?>">User Guide &amp; Book</a></li>
              </ul>
            </dd>
          </dl>

          <dl class="related">
            <dt>Get Help</dt>
            <dd>
              <ul>
                <li><a href="<?php echo $this->url(array('controller'=>'documentation', 'action'=>'index'), 'docs'); ?>">Documentation</a></li>
                <li><a href="<?php echo $this->url(array('controller'=>'contact', 'action'=>'index'), 'default'); ?>">Contact</a></li>
                <li><a href="<?php echo $this->url(array('controller'=>'bug', 'action'=>'index'), 'bugs'); ?>">Report a Bug</a></li>
                <li><a href="http://groups.google.com/group/swiftmailer">Google Group</a></li>
              </ul>
            </dd>
          </dl>
          
          <dl class="thanks">
            <dt>Thanks to</dt>
            <dd>
              <ul>
                <li><a href="http://github.com/">github</a></li>
                <li><a href="http://lighthouseapp.com/">Lighthouse</a></li>
                <li><a href="http://forums.devnetwork.net/">devnetwork.net</a></li>
              </ul>
            </dd>
          </dl>
            
            </div>
            
          </div>
        </div>
        
      </div>
      
    </div>
    
    </div>
  </body>
</html>
