<?php

/**
 * User class from swiftmailer.org - auto-generated by Doctrine ORM.
 * 
 * @author Chris Corbyn
 */
class User extends BaseUser
{
  
  /**
   * Set the user's password and generate hash + salt.
   * 
   * @param string $password
   */
  public function setPassword($password)
  {
    $salt = $this->_getSalt();
    $this->setPasswordSalt($salt);
    $this->setPasswordHash(md5(md5($password) . $salt));
  }
  
  // -- Private Methods
  
  private function _getSalt()
  {
    return pack('C*', rand(0, 255), rand(0, 255), rand(0, 255));
  }
  
}
