# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 28 Dec 2006 21:19:24 +0000
*               @ALL          1
*               @admin      255
*	@user	1
