<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings 
 * Auto-generated by config plugin 
 * Run for user: d11wtq
 * Date: Mon, 09 Mar 2009 02:13:20 +0000
 */

$conf['title'] = 'SwiftMailer Docs';
$conf['license'] = 'gnufdl';
$conf['breadcrumbs'] = 0;
$conf['useheading'] = '1';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['profileconfirm'] = 0;
$conf['disableactions'] = 'backlink,recent,revisions,source,export_raw';
$conf['userewrite'] = '1';
$conf['useslash'] = 1;

// end auto-generated content
