<?php $this->headLink()->appendStylesheet('/css/download.css'); ?>

<div id="container">
  <div id="content">
    
    <h1>Download Archive</h1>
    
    <?php if (count($this->downloads) == 0): ?>
      <p>
        There are currently no downloads in the system.  You may add one using the form shown above.
      </p>
    <?php else: ?>
      <table id="downloadadmin">
        <thead>
          <tr>
            <th>Filename</th>
            <th>Version</th>
            <th>Released</th>
            <th>Size</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($this->downloads as $download): ?>
            <tr id="download_<?php echo $this->escape($download->getDownloadId()); ?>">
              <td><a href="<?php echo $this->url(array(
                'controller'=>'download',
                'action'=>'download-file',
                'filename'=>$download->getName()),
                'get-download'
              ); ?>"><?php echo $this->escape($download->getName()); ?></a></td>
              <td><?php echo $this->escape($download->getVersion()); ?></td>
              <td><?php echo $this->escape(date('j M Y', $download->getTimeCreated())); ?></td>
              <td><?php echo $this->escape(number_format($download->getSize())); ?> bytes</td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    <?php endif; ?>
    
  </div>
</div>

<div id="sidepanel">
  <div class="supplementary corners top right bottom left">
    <h2>Source Code Repository Access</h2>
    <p>
      If you want to keep up-to-date with the very latest developments as they happen you
      can install and use Swift Mailer directly from <a href="http://github.com/swiftmailer/swiftmailer">our source code repository</a>, which
      currently uses Git and is hosted over at <a href="http://github.com/swiftmailer/swiftmailer">GitHub</a>.
    </p>
  </div>
</div>
