<div id="container">
  <div id="content">
    <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget risus. Phasellus ullamcorper, lectus et tincidunt porttitor, diam eros imperdiet libero, sed venenatis erat nisi quis nisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec eu justo ut risus dictum egestas. Vivamus rutrum, orci et consequat placerat, nibh mauris sodales ante, ac ultricies odio lacus vel quam. Vivamus ultricies orci ut libero. Fusce adipiscing sagittis nisi. Nullam in odio vitae urna tristique volutpat. Aliquam ligula. Curabitur blandit dolor quis enim.
    </p>
    <p>
      Nunc non enim ac nibh molestie aliquam. Donec sed eros. Integer vel velit vitae nisl sagittis posuere. Suspendisse potenti. Ut tincidunt. Praesent sed mi. Pellentesque ut arcu sed dolor pretium hendrerit. Donec mi est, dignissim a, porta ut, tincidunt eget, erat. Duis vitae purus sit amet justo lacinia dictum. Praesent a orci. Donec vel ipsum a sem viverra molestie. Nullam pretium, sapien eget convallis sagittis, nisi libero viverra lectus, non vulputate velit lacus non ligula. Mauris auctor. Nam vestibulum, ligula ut hendrerit tincidunt, risus mi faucibus lorem, ut iaculis dolor dui sit amet mi. Cras tortor. Nunc ut massa eu lectus pharetra adipiscing. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aenean leo. Nunc ut metus vel lectus mattis ultrices. Praesent sed orci.
    </p>
    <p>
      Aenean odio ligula, scelerisque quis, hendrerit at, suscipit id, nunc. Fusce rhoncus vestibulum turpis. Aliquam at neque sit amet massa vulputate lobortis. Duis dictum elit a leo. Suspendisse commodo justo non sapien. Aenean et leo. Nunc vitae lorem ut massa blandit venenatis. Praesent venenatis risus sit amet urna. Nullam aliquam lorem id enim. Duis viverra. Fusce eget velit et lorem rhoncus sollicitudin. Phasellus bibendum leo. Pellentesque ullamcorper urna sit amet lorem. Pellentesque fermentum consequat dolor.
    </p>
  </div>
</div>

<div id="sidepanel">
  <div class="supplementary corners top right bottom left">
    <p>
      Right
    </p>
    <p>
      Right
    </p>
    <p>
      Right
    </p>
    <p>
      Right
    </p>
    <p>
      Right
    </p>
    <p>
      Right
    </p>
    <p>
      Right
    </p>
    <p>
      Right
    </p>
    <p>
      Right
    </p>
    <p>
      Right
    </p>
    <p>
      Right
    </p>
    <p>
      Right
    </p>
  </div>
</div>
