<div id="container">
  <div id="content">
    
    <h1>Downloads</h1>
    
  </div>
</div>

<div id="sidepanel">
  <div class="supplementary corners top right bottom left">
    <p>
      Right
    </p>
    <p>
      Right
    </p>
    <p>
      Right
    </p>
    <p>
      Right
    </p>
    <p>
      Right
    </p>
    <p>
      Right
    </p>
    <p>
      Right
    </p>
    <p>
      Right
    </p>
    <p>
      Right
    </p>
    <p>
      Right
    </p>
    <p>
      Right
    </p>
    <p>
      Right
    </p>
  </div>
</div>
