<div id="container">
  <div id="content">
    
    <h1>Downloads</h1>
    
    <p>
      This page will take shape quickly as soon as the front-end for the Download
      Manager is complete under the admin area.  Backend code for the Downloads is
      complete (all the "Download*" classes).
    </p>
    
  </div>
</div>

<div id="sidepanel">
  <div class="supplementary corners top right bottom left">
    <p>
      Right
    </p>
    <p>
      Right
    </p>
    <p>
      Right
    </p>
    <p>
      Right
    </p>
    <p>
      Right
    </p>
    <p>
      Right
    </p>
    <p>
      Right
    </p>
    <p>
      Right
    </p>
    <p>
      Right
    </p>
    <p>
      Right
    </p>
    <p>
      Right
    </p>
    <p>
      Right
    </p>
  </div>
</div>
