<?php $this->headLink()->appendStylesheet('/css/admin.css'); ?>

<div id="container">
  <div id="content">
    
    <h1>Download Manager</h1>
    
    <p>
      From here you can view the list of downloads added for public consumption.  You
      can revoke these downloads (in the event of say a really critical bug) and you
      can add to them.
    </p>
    
    <p>
      In order to add a download it must first exist at either SourceForge, Google Code
      or GitHub.  This Download Manager will lookup the details of the package from
      the remote resource.
    </p>
    
    <h2>Add a new download</h2>
    
    <?php require('fragments/_validation-errors.phtml'); ?>
    
    <form id="adddownloadform" action="" method="post">
      <fieldset class="downloadfields">
        <label for="field_filename">
          <strong>Package Filename</strong>
          <span class="instruction">
            You need to specify the full name of the file that is available for download
          </span>
        </label>
        <input type="text" class="text" id="field_filename" <?php echo $this->formAttributes('input', 'filename'); ?> />
        
        <label for="field_sources">
          <strong>Download Location</strong>
          <span class="instruction">
            Downloads must be hosted at a third-party site. The download manager will determine
            the correct link for the remote file.
          </span>
        </label>
        <fieldset id="field_sources" class="radios">
          <label for="field_source_sourceforge">
            <input type="radio" class="radio" id="field_source_sourceforge" <?php echo $this->formAttributes('radio', 'source', 'sourceforge'); ?> />
            SourceForge
          </label>
          <label for="field_source_googlecode">
            <input type="radio" class="radio" id="field_source_googlecode" <?php echo $this->formAttributes('radio', 'source', 'googlecode'); ?> />
            Google Code
          </label>
          <label for="field_source_github">
            <input type="radio" class="radio" id="field_source_github" <?php echo $this->formAttributes('radio', 'source', 'github'); ?> />
            GitHub
          </label>
        </fieldset>
      </fieldset>
      
      <fieldset class="buttons">
        
        <input type="submit" class="primary button" name="add" value="Add Download" />
        
      </fieldset>
    </form>
    
    <h2>All downloads</h2>
    
    <?php if (count($this->downloads) == 0): ?>
      <p>
        There are currently no downloads in the system.  You may add one using the form shown above.
      </p>
    <?php else: ?>
      <table id="downloadadmin">
        <thead>
          <tr>
            <th>Filename</th>
            <th>Release Date</th>
            <th>File Size</th>
            <th>Location</th>
            <th>Stable?</th>
            <th>Revoked?</th>
            <th>Edit</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($this->downloads as $download): ?>
            <tr id="download_<?php echo $this->escape($download->getDownloadId()); ?>">
              <td><?php echo $this->escape($download->getName()); ?></td>
              <td><?php echo $this->escape(date('j M Y', $download->getTimeCreated())); ?></td>
              <td><?php echo $this->escape(number_format($download->getSize())); ?> bytes</td>
              <td>
                <?php if ($download->getSource() == 'sourceforge'): ?>
                  SourceForge
                <?php elseif ($download->getSource() == 'googlecode'): ?>
                  Google Code
                <?php elseif ($download->getSource() == 'github'): ?>
                  GitHub
                <?php else: ?>
                  Unknown
                <?php endif; ?>
              </td>
              <td><?php echo $this->escape($download->isStable() ? 'Yes' : 'No'); ?></td>
              <td><?php echo $this->escape($download->isRevoked() ? 'Yes' : 'No'); ?></td>
              <td><a href="<?php echo $this->url(array('controller'=>'admin', 'action'=>'edit-download', 'downloadid'=>$download->getDownloadId()), 'edit-download'); ?>">Edit</a></td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    <?php endif; ?>
    
  </div>
</div>

<?php require('fragments/_admin-menu.phtml'); ?>
