<?php $this->headLink()->appendStylesheet('/css/admin.css'); ?>

<div id="container">
  <div id="content">
    
    <h1>Swift Mailer Administration</h1>
    
    <p>
      The administration area gives you the ability to add new releases (via
      SourceForge, Google Code or GitHub), grant users access and to monitor
      our download statistics.
    </p>
    
    <p>
      You should not grant access to users without agreements from the rest of
      the team.
    </p>
    
    <p>
      <strong>If this is the first time you have logged in, please change your
        password immediately</strong>.
    </p>
    
  </div>
</div>

<?php require('fragments/_admin-menu.phtml'); ?>
