<?php $this->headLink()->appendStylesheet('/css/admin.css'); ?>

<div id="container">
  <div id="content">
    
    <h1>Administrator Login</h1>
    
    <p>
      You must login before you can proceed.  If you have forgotten your password
      you will need to contact another administrator for a password reset.
    </p>
    
    <?php require('fragments/_validation-errors.phtml'); ?>
    
    <form id="loginform" action="" method="post">
      <fieldset class="loginfields">
        <label for="field_username">
          <strong>Username</strong>
        </label>
        <input type="text" class="text" name="username" id="field_username" value="" />
        
        <label for="field_password">
          <strong>Password</strong>
        </label>
        <input type="password" class="text" name="password" id="field_username" value="" />
      </fieldset>
      
      <fieldset class="buttons">
        
        <input type="submit" class="primary button" name="login" value="Login" />
        <input type="submit" class="secondary button" name="cancel" value="Cancel" />
        
      </fieldset>
    </form>
    
  </div>
</div>


