<?php $this->headLink()->appendStylesheet('/css/admin.css'); ?>

<div id="container">
  <div id="content">
    
    <h1>Password Change (<?php echo $this->escape($this->user->getUsername()); ?>)</h1>
    
    <p>
      It is advised that you change your password regularly.
    </p>
    
    <?php require('fragments/_validation-errors.phtml'); ?>
    
    <form id="changepasswordform" action="" method="post">
      <fieldset class="currentpassword">
        <label for="field_currentpassword">
          <strong>Current Password</strong>
          <span class="instruction">
            You need to provide your password again before you can change it
          </span>
        </label>
        <input type="password" class="text" name="currentpassword" id="field_currentpassword" value="" />
      </fieldset>
      
      <fieldset class="newpassword">
        <label for="field_newpassword0">
          <strong>New Password</strong>
        </label>
        <input type="password" class="text" name="newpassword0" id="field_newpassword0" value="" />
        
        <label for="field_newpassword1">
          <strong>Repeat Password</strong>
        </label>
        <input type="password" class="text" name="newpassword1" id="field_newpassword1" value="" />
      </fieldset>
      
      <fieldset class="buttons">
        
        <input type="submit" class="primary button" name="submit" value="Change Password" />
        <input type="submit" class="secondary button" name="cancel" value="Cancel" />
        
      </fieldset>
    </form>
    
  </div>
</div>

<?php require('fragments/_admin-menu.phtml'); ?>
